import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
    return (
        <Html lang="en">
            <Head>
                <title>SkyScope</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <meta
                    name="description"
                    content="Astronomy Images and Videos "
                />
            </Head>

            <body>
                <Main />
                <NextScript />
            </body>
            
        </Html>
    );
}
